/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function optimize(svg: string, options?: OptimizeOptions | undefined | null): OptimizeResult

export interface OptimizeOptions {
  preset?: string
  precision?: number
  passes?: Record<string, boolean>
}

export interface OptimizeResult {
  data: string
  iterations: number
}

export declare function version(): string
